version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile  # Single Dockerfile for combined services
    ports:
      - "8080:8080"  # Map Nginx port to host
    env_file:
      - .env  # Pass environment variables
    volumes:
      - .:/app  # Mount the project directory for development
