# Use Node.js for frontend
FROM node:18

WORKDIR /app

# Install frontend dependencies
COPY package*.json ./
RUN npm install

# Copy React source code and build the app
COPY public ./public
COPY src ./src
RUN npm run build

# Use an Nginx base image to serve the frontend
FROM nginx:1.22
COPY --from=0 /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Expose frontend port
EXPOSE 8080

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
