version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Single exposed port for Cloud Run or local testing
    env_file:
      - .env
    volumes:
      - .:/app # Mount the project directory to the container for development
    command: >
      sh -c "uvicorn backend.embeddingsFetch:app --host 0.0.0.0 --port 8000 &
             npm start --prefix /app &
             nginx -g 'daemon off;'"